import{useEffect,useState}from'react'

const menu=[
 {group:'Small plates',items:[['Dahi papdi','Charred corn, date chutney, smoked chilli','₹425'],['Kashmiri morels','Walnut, lotus stem, fennel broth','₹695']]},
 {group:'From the fire',items:[['Kasundi sea bass','Green mango, mustard leaf, lemon rice','₹975'],['Mutton pepper fry','Tellicherry pepper, curry leaf, appam','₹895']]},
 {group:'Garden',items:[['Jackfruit galouti','Sheermal, pickled shallot, mint','₹545'],['Pumpkin khichda','Foxtail millet, brown butter, crisp sage','₹495']]}
]
const notes=[['Asha Menon','Food writer, Bengaluru','Every course felt rooted in memory, then sharpened by a curious kitchen.'],['Rohan and Leena','Friday dinner guests','The grill counter seats are the best place to watch dinner take shape.']]

function Mark(){return <svg viewBox="0 0 44 44" aria-hidden="true"><path d="M22 3c6 8 8 13 8 19a8 8 0 0 1-16 0c0-6 3-12 8-19Z" fill="none" stroke="currentColor" strokeWidth="1.5"/><path d="M13 29c7-4 12-4 18 0M22 12v23" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>}
function DishArt(){return <svg className="hero-art" viewBox="0 0 640 720" role="img" aria-label="Illustration of a plated modern Indian dish"><defs><radialGradient id="plate"><stop stopColor="var(--bw-text)"/><stop offset="1" stopColor="color-mix(in srgb,var(--bw-text) 40%,var(--bw-surface))"/></radialGradient></defs><circle cx="320" cy="355" r="260" fill="none" stroke="var(--bw-accent)" strokeOpacity=".22"/><circle cx="320" cy="355" r="198" fill="url(#plate)"/><path d="M193 373c52-89 179-115 263-43-43 93-191 130-263 43Z" fill="var(--bw-accent)"/><path d="M233 341c38 1 84 23 112 62M295 302c7 27 0 52-19 72M383 315c-15 21-17 50-5 78" fill="none" stroke="var(--bw-surface)" strokeWidth="8" strokeLinecap="round"/><g fill="var(--bw-surface)"><circle cx="248" cy="388" r="9"/><circle cx="363" cy="350" r="7"/><circle cx="412" cy="386" r="11"/></g><path d="M463 185c-29 22-47 50-55 83 32-11 53-35 55-83ZM177 513c39-8 65-2 90 20-34 14-64 7-90-20Z" fill="var(--bw-accent)"/><text x="320" y="670" textAnchor="middle" fill="var(--bw-muted)" fontSize="15" letterSpacing="5">FIRE · SPICE · SEASON</text></svg>}

export default function App(){const[open,setOpen]=useState(false);useEffect(()=>{const nodes=document.querySelectorAll('[data-reveal]');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('seen');io.unobserve(e.target)}}),{threshold:.12});nodes.forEach(n=>io.observe(n));return()=>io.disconnect()},[]);return <div>
 {/* Source slug: hyperui-headers-4 | Author: https://github.com/markmead/hyperui */}
 <header className="site-head"><a className="brand" href="#top"><span><Mark/></span><b>SAFFRON TRAIL<small>MODERN INDIAN DINING</small></b></a><nav><a href="#menu">Menu</a><a href="#story">Our kitchen</a><a href="#visit">Visit</a></nav><a className="button small" href="#reserve">Reserve</a><button className="nav-toggle" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?'×':'Menu'}</button>{open&&<div className="mobile"><a href="#menu">Menu</a><a href="#story">Our kitchen</a><a href="#visit">Visit</a><a href="#reserve">Reserve</a></div>}</header>
 <main>
 {/* Source slug: meraki-hero-side-image | Author: https://github.com/merakiui/merakiui */}
 <section id="top" className="hero shell"><div data-reveal><p className="eyebrow">Indiranagar · Bengaluru</p><h1>India,<br/><em>in a new light.</em></h1><p className="lead">Regional recipes meet a live charcoal kitchen, seasonal produce, and the easy pace of a long dinner.</p><div className="actions"><a className="button" href="#reserve">Reserve a table</a><a className="link" href="#menu">Explore the menu ↘</a></div><div className="hero-note"><strong>Dinner</strong> Tue to Sun, 6:00 pm to 11:30 pm</div></div><div className="art-wrap" data-reveal><DishArt/><span className="seal">Tasting menu<br/><b>₹2,850</b></span></div></section>
 {/* Source slug: hyperui-feature-grids-2 | Author: https://github.com/markmead/hyperui */}
 <section id="story" className="section rule"><div className="shell intro" data-reveal><p className="eyebrow">The Saffron Trail table</p><h2>Familiar flavours.<br/><em>Fresh perspective.</em></h2><p>Chef Anika Rao follows ingredients across the subcontinent, from Kodagu pepper to Kashmiri morels. The result is precise, generous food without ceremony.</p></div><div className="shell feature-grid"><article data-reveal><b>01</b><h3>Charcoal kitchen</h3><p>Seafood, vegetables, and breads cooked over mango wood in full view of the dining room.</p></article><article data-reveal><b>02</b><h3>Season-led menu</h3><p>Small farms and short harvests guide a menu that changes often without losing its roots.</p></article><article data-reveal><b>03</b><h3>Indian cellar</h3><p>Low-intervention wines, botanical highballs, and alcohol-free pairings built around spice.</p></article></div></section>
 {/* Source slug: tripled-gallery-grid-block-shadcnui | Author: https://github.com/moumen-soliman/uitripled */}
 <section id="menu" className="section menu-section"><div className="shell"><div className="section-head" data-reveal><div><p className="eyebrow">Dinner menu</p><h2>A route through<br/><em>regional kitchens.</em></h2></div><p>À la carte plates are designed to share. Vegetarian and gluten-aware choices are always available.</p></div><div className="menu-grid">{menu.map((g,i)=><article key={g.group} data-reveal><span>0{i+1}</span><h3>{g.group}</h3>{g.items.map(([n,d,p])=><div className="menu-item" key={n}><div><b>{n}</b><small>{d}</small></div><strong>{p}</strong></div>)}</article>)}</div><p className="fine">Prices exclude 5% GST. Please tell our team about allergies when reserving.</p></div></section>
 {/* Source slug: meraki-testimonials-full-page-cards | Author: https://github.com/merakiui/merakiui */}
 <section className="section shell"><div className="quote-grid">{notes.map(([n,r,q])=><figure data-reveal key={n}><span>“</span><blockquote>{q}</blockquote><figcaption><b>{n}</b><small>{r}</small></figcaption></figure>)}</div></section>
 {/* Source slug: hyperui-contact-forms-2 | Author: https://github.com/markmead/hyperui */}
 <section id="visit" className="section visit"><div className="shell visit-grid"><div data-reveal><p className="eyebrow">Find us</p><h2>Dinner in<br/><em>Indiranagar.</em></h2><p className="lead small-lead">18 Defence Colony, 12th Main, Bengaluru 560038</p><a className="link" href="mailto:hello@saffrontrail.example">hello@saffrontrail.example</a></div><div className="map" data-reveal><svg viewBox="0 0 600 400" aria-label="Illustrated map to Saffron Trail"><path d="M-20 80 620 260M125-20l230 440M430-20l-70 440"/><path className="accent-road" d="M-20 320 620 115"/><circle cx="365" cy="197" r="24"/><text x="365" y="202">ST</text><text x="40" y="58">12TH MAIN</text><text x="410" y="335">100 FT ROAD</text></svg></div><div className="hours" data-reveal><span><b>Tuesday to Thursday</b><small>6:00 pm to 11:00 pm</small></span><span><b>Friday to Sunday</b><small>6:00 pm to 11:30 pm</small></span><span><b>Monday</b><small>Closed</small></span></div></div></section>
 {/* Source slug: meraki-cta-card | Author: https://github.com/merakiui/merakiui */}
 <section id="reserve" className="cta"><div className="shell" data-reveal><p className="eyebrow">Your table is waiting</p><h2>Come hungry.<br/><em>Leave curious.</em></h2><p>Reservations open 30 days ahead. For groups of nine or more, our dining team can plan a shared feast.</p><div className="actions center"><a className="button inverse" href="mailto:tables@saffrontrail.example?subject=Reservation">Reserve by email</a><a className="link inverse-link" href="tel:+918041285500">+91 80 4128 5500</a></div></div></section>
 </main>
 {/* Source slug: hyperui-footers-2 | Author: https://github.com/markmead/hyperui */}
 <footer><div className="shell footer-grid"><div className="brand"><span><Mark/></span><b>SAFFRON TRAIL<small>MODERN INDIAN DINING</small></b></div><p>Regional Indian food, seen through a Bengaluru kitchen.</p><div><a href="#menu">Menu</a><a href="#visit">Hours</a><a href="#reserve">Reservations</a></div></div><div className="shell footnote"><span>© 2026 Saffron Trail. Fictional business.</span><span>18 Defence Colony, Bengaluru</span></div></footer>
 </div>}
