import { useState } from 'react'

const stories=[
  ['Design','The quiet return of repairable electronics','Inside the workshops making everyday devices understandable again.','12 min'],['Cities','A night bus can change who a city belongs to','Five routes, three drivers, and the public life after midnight.','8 min'],['Food','The neighborhood bakery as climate infrastructure','Small ovens, local grain, and a different model for resilient streets.','7 min'],['Technology','What happens when software learns to wait','The case for slower defaults in an age of instant output.','10 min'],['Work','The new apprenticeship is hiding in plain sight','Why small studios are rebuilding the path into skilled work.','6 min'],['Culture','A field guide to the independent cinema revival','Six rooms proving that moviegoing still has a future.','9 min'],
]
const sections=['Latest','Design','Cities','Food','Technology','Work','Culture']

export default function App(){const[section,setSection]=useState('Latest');const[email,setEmail]=useState('');const[joined,setJoined]=useState(false);const filtered=section==='Latest'?stories:stories.filter(story=>story[0]===section)
  return <div className="magazine-app"><header className="mag-head"><div className="mag-utility"><span>Issue 28 · Autumn 2026</span><span>Independent reporting on how we live now</span><a href="#newsletter">Newsletter</a></div><a className="masthead" href="#latest">RELAY REVIEW</a><div className="mag-nav"><button type="button" aria-label="Open magazine menu">☰</button><nav aria-label="Sections">{sections.map(item=><a href="#latest" aria-current={section===item?'page':undefined} onClick={()=>setSection(item)} key={item}>{item}</a>)}</nav><button type="button" aria-label="Search Relay Review">⌕</button></div></header>
    <main id="latest"><section className="lead-story"><div className="lead-image" role="img" aria-label="Geometric editorial illustration of a public library interior"><span>28</span><i/><b/><small>PHOTOGRAPHY<br/>LINA VEGA</small></div><article><p className="eyebrow">Cover story · Public life</p><h1>The library that stayed open after everything else closed.</h1><p className="dek">In one coastal town, a late-night library became a classroom, cooling center, newsroom, and the last warm room with no expectation to buy.</p><div className="byline"><span className="avatar">AR</span><p><b>Amara Reed</b><small>18 minute read · August 18</small></p></div><a className="text-link" href="#stories">Read the cover story →</a></article></section>
      <section id="stories" className="story-section"><div className="story-head"><div><p className="label">The current issue</p><h2>{section === 'Latest' ? 'Stories worth your time' : section}</h2></div><div className="issue-tabs" aria-label="Filter articles">{sections.map(item=><button type="button" aria-pressed={section===item} onClick={()=>setSection(item)} key={item}>{item}</button>)}</div></div><div className="story-layout"><div className="story-grid">{filtered.map((story,index)=><article className="story" key={story[1]}><div className={'story-art art-'+((stories.indexOf(story)%4)+1)}><span>0{stories.indexOf(story)+1}</span><i/></div><p className="eyebrow">{story[0]}</p><h3><a href="#article">{story[1]}</a></h3><p>{story[2]}</p><small>{story[3]} read</small></article>)}</div><aside className="trending"><p className="label">Most read this week</p>{stories.slice(0,4).map((story,index)=><a href="#article" key={story[1]}><span>0{index+1}</span><p><b>{story[1]}</b><small>{story[0]} · {story[3]}</small></p></a>)}</aside></div></section>
      <section id="newsletter" className="newsletter"><div><p className="eyebrow">The Sunday Relay</p><h2>One considered email.<br/>No infinite scroll.</h2><p>Our editors send the week’s essential story, a useful link, and one reason to leave the house.</p></div>{joined?<p className="joined" role="status">You’re on the list. Look for Relay on Sunday.</p>:<form onSubmit={event=>{event.preventDefault();if(email)setJoined(true)}}><label htmlFor="email">Email address</label><div><input id="email" type="email" required value={email} onChange={event=>setEmail(event.target.value)} placeholder="you@example.com"/><button className="button" type="submit">Join free</button></div><small>Free forever · Unsubscribe in one click</small></form>}</section>
    </main><footer><b>RELAY REVIEW</b><span>Independent since 2018</span><nav><a href="#latest">About</a><a href="#latest">Contributors</a><a href="#newsletter">Newsletter</a></nav></footer>
  </div>
}
