import { useEffect, useState } from 'react'

function Reveals(){useEffect(()=>{const n=[...document.querySelectorAll('[data-reveal]')];if(matchMedia('(prefers-reduced-motion: reduce)').matches||!('IntersectionObserver'in window)){n.forEach(x=>x.classList.add('visible'));return}const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.12});n.forEach(x=>o.observe(x));return()=>o.disconnect()},[]);return null}

// Source slug: hyperui-headers-4
// Author repo: https://github.com/markmead/hyperui
function Nav(){const[open,setOpen]=useState(false);const links=[['Advisory','#services'],['Engagements','#engagements'],['Method','#method'],['Firm','#firm']];return <header className="nav"><div className="shell nav-row"><a className="brand" href="#top"><span>ML</span><strong>Meridian Ledger Advisors<small>Finance for operating decisions</small></strong></a><nav className="desktop">{links.map(x=><a href={x[1]} key={x[1]}>{x[0]}</a>)}<a className="button small" href="#contact">Book a working session</a></nav><button className="menu" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Close':'Menu'}</button></div>{open&&<nav className="mobile">{links.map(x=><a href={x[1]} key={x[1]}>{x[0]}</a>)}<a href="#contact">Book a working session</a></nav>}</header>}

function LedgerArt(){const bars=[42,58,47,66,72,63,81,76,88,94,86,103];return <svg className="ledger-art" viewBox="0 0 760 580" role="img" aria-label="Twelve-month cash forecast and operating margin dashboard"><rect width="760" height="580" rx="26" fill="color-mix(in srgb,var(--bw-surface) 92%,var(--bw-text))"/><path d="M46 82H714M46 500H714" stroke="var(--bw-text)" opacity=".14"/><text x="48" y="54" fill="var(--bw-muted)" fontFamily="monospace" fontSize="13">13-WEEK CASH / BASE CASE</text><text x="660" y="54" fill="var(--bw-accent)" fontFamily="monospace" fontSize="13">UPDATED</text><g transform="translate(55 116)">{bars.map((h,i)=><rect key={i} x={i*52} y={230-h*2} width="28" height={h*2} rx="4" fill={i>8?'var(--bw-accent)':'color-mix(in srgb,var(--bw-accent) 32%,transparent)'}/>)}</g><path d="M55 315C145 280 190 290 250 250S355 205 420 220s115-15 165-65 86-26 125-65" fill="none" stroke="var(--bw-text)" strokeWidth="5"/><circle cx="710" cy="90" r="9" fill="var(--bw-accent)"/><g transform="translate(55 440)"><text fill="var(--bw-muted)" fontFamily="monospace" fontSize="12">RUNWAY</text><text y="38" fill="var(--bw-text)" fontFamily="Arial" fontWeight="700" fontSize="28">14.2 months</text><text x="245" fill="var(--bw-muted)" fontFamily="monospace" fontSize="12">GROSS MARGIN</text><text x="245" y="38" fill="var(--bw-text)" fontFamily="Arial" fontWeight="700" fontSize="28">61.8%</text><text x="500" fill="var(--bw-muted)" fontFamily="monospace" fontSize="12">DECISION</text><text x="500" y="38" fill="var(--bw-accent)" fontFamily="Arial" fontWeight="700" fontSize="28">Hire in Q3</text></g></svg>}

// Source slug: motion-primitives-spotlight
// Author repo: https://github.com/ibelick/motion-primitives
function Hero(){return <section id="top" className="hero"><div className="shell hero-grid"><div data-reveal><p className="eyebrow">Independent finance advisory for founder-led companies</p><h1>Know the number.<br/><em>Make the call.</em></h1><p>Meridian Ledger Advisors turns finance data into operating decisions for growing teams. Cash, margin, hiring, pricing, and board reporting all connect in one useful view.</p><div className="actions"><a className="button" href="#contact">Schedule a 45-minute call <span>↗</span></a><a className="link" href="#engagements">See engagement options ↓</a></div><div className="hero-note"><strong>Based in New York · Working across the US</strong><span>Former operators, not outsourced bookkeepers.</span></div></div><div className="art-frame" data-reveal><LedgerArt/><span>Illustrative management view</span></div></div></section>}

// Source slug: hyperui-feature-grids-2
// Author repo: https://github.com/markmead/hyperui
const services=[['01','Forecasting that drives action','A rolling cash model tied to hiring, sales capacity, collections, and the decisions already on your calendar.'],['02','Margin and pricing clarity','Contribution margin by product, customer, and channel so growth is measured by quality, not noise.'],['03','Board and investor reporting','Concise monthly packages with the story behind the variance and an honest forward view.'],['04','Finance team design','The right close process, controls, systems, and roles for your current scale and next stage.']]
function Services(){return <section id="services" className="section services"><div className="shell"><div className="section-title" data-reveal><p className="eyebrow">What we solve</p><h2>Finance built for the operating room.</h2><p>No giant decks. We build a repeatable cadence that gives leadership a sharper view before each consequential decision.</p></div><div className="service-list">{services.map(x=><article key={x[0]} data-reveal><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>}

// Source slug: hyperui-stats-1
// Author repo: https://github.com/markmead/hyperui
function Stats(){return <section className="stats"><div className="shell stat-grid">{[['$180M+','Client revenue advised'],['11 yrs','Operator and CFO experience'],['8 days','Typical first model delivery'],['100%','Partner-led engagements']].map(x=><article data-reveal key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></article>)}</div></section>}

// Source slug: hyperui-pricing-1
// Author repo: https://github.com/markmead/hyperui
function Engagements(){return <section id="engagements" className="section engagements"><div className="shell"><div className="section-title" data-reveal><p className="eyebrow">Ways to work together</p><h2>A defined start. A useful outcome.</h2><p>Choose a focused diagnostic or ongoing finance leadership. Scope and deliverables are agreed before work begins.</p></div><div className="price-grid"><article data-reveal><span>Decision Sprint</span><strong>$9,500</strong><small>Three weeks · fixed fee</small><p>For a funding, hiring, pricing, or runway decision that needs a defensible model and recommendation.</p><ul><li>Leadership interviews and data review</li><li>Decision model with scenarios</li><li>Executive working session</li><li>90-day action memo</li></ul><a className="button ghost" href="#contact">Plan a sprint ↗</a></article><article className="featured" data-reveal><span>Embedded Finance Lead</span><strong>From $12,000</strong><small>Per month · three-month minimum</small><p>For teams that need senior finance leadership without a full-time CFO hire.</p><ul><li>Monthly close and management pack</li><li>Rolling cash and operating forecast</li><li>Weekly founder working session</li><li>Board preparation and attendance</li></ul><a className="button" href="#contact">Discuss a retainer ↗</a></article></div></div></section>}

// Source slug: meraki-testimonials-full-page-cards
// Author repo: https://github.com/merakiui/merakiui
function Method(){return <section id="method" className="section method"><div className="shell method-grid"><div data-reveal><p className="eyebrow">The working cadence</p><h2>Close the books.<br/>Open the decision.</h2><blockquote>“Meridian Ledger gave us one forecast the whole leadership team trusted. We stopped debating whose spreadsheet was right and made the capacity call in two meetings.”<footer><strong>Elena Brooks</strong><span>CEO, Northline Care</span></footer></blockquote></div><div className="method-list">{[['01','Baseline','Reconcile the source data, definitions, and current forecast.'],['02','Drivers','Identify the handful of operating inputs that actually move cash and margin.'],['03','Cadence','Set the monthly close, weekly updates, owners, and decision dates.'],['04','Challenge','Test assumptions, document tradeoffs, and recommend the next move.']].map(x=><article data-reveal key={x[0]}><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></div></section>}

// Source slug: hyperui-logo-wall-3
// Author repo: https://github.com/markmead/hyperui
function Firm(){return <section id="firm" className="section firm"><div className="shell firm-grid"><div data-reveal><p className="eyebrow">The firm</p><h2>Senior attention from first model to boardroom.</h2></div><div data-reveal><p>Meridian Ledger Advisors was founded by Maya Chen, former VP Finance at a venture-backed healthcare platform, and Thomas Reed, an operating CFO for software and services businesses.</p><div className="credentials"><span>CPA-led</span><span>FP&A operators</span><span>Board-ready</span><span>System agnostic</span></div></div></div></section>}

// Source slug: hyperui-faq-1
// Author repo: https://github.com/markmead/hyperui
function Faq(){const q=[['Are you a bookkeeping firm?','No. We coordinate with your bookkeeper or controller, but our work focuses on planning, performance, capital, and operating decisions.'],['What stage is the best fit?','Most clients have $3M to $75M in annual revenue, a leadership team, and decisions that have outgrown founder spreadsheets.'],['Can you help before a fundraise?','Yes. We can build the operating model, pressure-test the use of funds, and prepare management for financial diligence. We do not broker securities.']];return <section className="section faq"><div className="shell faq-grid"><h2 data-reveal>Questions worth asking.</h2><div>{q.map((x,i)=><details key={x[0]} open={i===0} data-reveal><summary>{x[0]}<span>+</span></summary><p>{x[1]}</p></details>)}</div></div></section>}

// Source slug: hyperui-ctas-4
// Author repo: https://github.com/markmead/hyperui
function Contact(){return <section id="contact" className="section contact"><div className="shell contact-grid" data-reveal><div><p className="eyebrow">Start with one decision</p><h2>What number is holding up the room?</h2><p>Tell us what you are deciding, your timing, and what the current finance view is missing. We will reply within one business day.</p></div><div><a className="button light" href="mailto:advisory@meridianledger.example">advisory@meridianledger.example ↗</a><a className="link" href="tel:+12125550184">+1 212 555 0184</a></div></div></section>}

// Source slug: hyperui-footers-4
// Author repo: https://github.com/markmead/hyperui
function Footer(){return <footer><div className="shell footer-grid"><div className="brand"><span>ML</span><strong>Meridian Ledger Advisors<small>Finance for operating decisions</small></strong></div><p>New York, NY · Serving clients across the United States</p><nav><a href="#services">Advisory</a><a href="#engagements">Engagements</a><a href="#contact">Contact</a></nav></div><div className="shell legal"><span>© 2026 Meridian Ledger Advisors. Fictional consulting firm.</span><span>Not affiliated with the Meridian finance app template.</span></div></footer>}

export default function App(){return <><Reveals/><Nav/><main><Hero/><Services/><Stats/><Engagements/><Method/><Firm/><Faq/><Contact/></main><Footer/></>}
