import { useState } from 'react'

const schedule={
  'Day 1':[['09:00','Opening: What should technology make possible?','Main hall','Mira Okafor'],['11:00','Designing public systems people can trust','Studio A','Eli Navarro'],['14:00','Workshop: Prototype the policy, not just the screen','Lab 2','Sana Ito'],['17:30','City walk and opening supper','Courtyard','All speakers']],
  'Day 2':[['09:30','The business case for humane defaults','Main hall','Jonas Berg'],['11:30','Small models, local knowledge','Studio B','Kavya Menon'],['15:00','Building teams that can change their mind','Main hall','Amina Cole'],['19:00','Independent tools showcase','Warehouse','12 makers']],
  'Day 3':[['10:00','Repair, maintenance, and the long product life','Main hall','Rui Santos'],['12:00','Workshop: A field guide to useful metrics','Lab 1','Noah Williams'],['15:30','Closing assembly: commitments for Monday','Main hall','Community'],['17:00','Farewell tea','Courtyard','Everyone']],
}
const speakers=[['MO','Mira Okafor','Civic technologist','Lagos'],['KM','Kavya Menon','AI researcher','Bengaluru'],['EN','Eli Navarro','Service designer','Barcelona'],['AC','Amina Cole','Organizational builder','Detroit']]

export default function App(){const[day,setDay]=useState('Day 1');const[saved,setSaved]=useState(new Set());const toggle=index=>setSaved(current=>{const next=new Set(current);next.has(index)?next.delete(index):next.add(index);return next})
  return <div className="event-app"><header className="event-head"><a className="brand" href="#top"><span>CG</span><b>COMMON<br/>GROUND</b></a><nav aria-label="Primary"><a href="#program">Program</a><a href="#speakers">Speakers</a><a href="#venue">Venue</a></nav><a className="button" href="#tickets">Get a pass</a></header>
    <main id="top"><section className="event-hero"><div className="event-copy"><p className="eyebrow">Lisbon · 14–16 October 2026</p><h1>Make things<br/><em>worth keeping.</em></h1><p>Three days for people building technology, services, and organizations with a longer view. Practical sessions, serious questions, generous rooms.</p><div><a className="button" href="#tickets">Get your pass · €320</a><a className="text-link" href="#program">See the program ↓</a></div><small>420 seats · 38 speakers · 3 working days</small></div><div className="event-poster" role="img" aria-label="Common Ground conference geometric poster"><span>COMMON</span><b>GROUND</b><i>14—16<br/>OCT<br/>LISBON</i><small>CG<br/>26</small></div></section>
      <section className="marquee" aria-label="Conference themes"><span>PUBLIC TECHNOLOGY</span><span>RESPONSIBLE AI</span><span>SERVICE DESIGN</span><span>INDEPENDENT TOOLS</span></section>
      <section id="program" className="program"><div className="section-head"><div><p className="label">Program</p><h2>Leave with work<br/>you can use.</h2></div><p>Every session is designed around a decision, practice, or prototype—not a product pitch.</p></div><div className="day-tabs" aria-label="Conference day">{Object.keys(schedule).map((item,index)=><button type="button" aria-pressed={day===item} onClick={()=>setDay(item)} key={item}><span>0{index+1}</span>{item}<small>{14+index} Oct</small></button>)}</div><div className="schedule">{schedule[day].map((item,index)=><article key={item[1]}><time>{item[0]}</time><div><p className="eyebrow">{item[2]}</p><h3>{item[1]}</h3><span>{item[3]}</span></div><button type="button" aria-pressed={saved.has(index)} onClick={()=>toggle(index)} aria-label={(saved.has(index)?'Remove ':'Save ')+item[1]}>{saved.has(index)?'Saved ✓':'Save +'}</button></article>)}</div></section>
      <section id="speakers" className="speakers"><div className="section-head"><div><p className="label">Featured speakers</p><h2>People doing<br/>the patient work.</h2></div><a className="text-link" href="#speakers">Meet all 38 speakers →</a></div><div className="speaker-grid">{speakers.map((speaker,index)=><article key={speaker[1]}><div className={'speaker-art speaker-'+(index+1)}><span>{speaker[0]}</span><i/></div><h3>{speaker[1]}</h3><p>{speaker[2]} · {speaker[3]}</p></article>)}</div></section>
      <section id="tickets" className="tickets"><div><p className="eyebrow">Final release · 84 passes remain</p><h2>Three useful days.<br/>One generous room.</h2></div><div><strong>€320</strong><span>Includes all sessions, workshops, lunch, opening supper, and recordings.</span><a className="button inverse" href="mailto:hello@commonground.example">Reserve a pass</a></div></section>
    </main><footer id="venue"><b>COMMON GROUND</b><p>Beato Innovation District · Lisbon</p><nav><a href="#program">Code of conduct</a><a href="#venue">Travel</a><a href="mailto:hello@commonground.example">Contact</a></nav></footer>
  </div>
}
