import { useMemo, useState } from 'react'

const products=[
  ['Arc Table Lamp','Morrow Studio','$240','Lighting','New','#E4B778'],['Folded Steel Chair','Kita Works','$390','Furniture','Few left','#6C7B66'],['Ridge Carafe','Sora Glass','$128','Tableware','Bestseller','#A8C5C3'],['Column Speaker','Ordinary Objects','$560','Audio','New','#B8907D'],['Wool Study Rug','Northern Loom','$420','Textiles','Handmade','#C4A56D'],['Pocket Tray Set','Field Office','$76','Objects','Set of 3','#8C7769'],
]
const categories=['All','Furniture','Lighting','Tableware','Audio','Textiles','Objects']

export default function App(){const[query,setQuery]=useState('');const[category,setCategory]=useState('All');const[saved,setSaved]=useState(new Set());const visible=useMemo(()=>products.filter(item=>(category==='All'||item[3]===category)&&item[0].toLowerCase().includes(query.toLowerCase())),[query,category]);const toggle=index=>setSaved(current=>{const next=new Set(current);next.has(index)?next.delete(index):next.add(index);return next})
  return <div className="market-app"><header className="market-head"><div className="topline"><span>Objects for thoughtful rooms</span><span>Free delivery over $150 · 30-day returns</span></div><div className="market-nav"><a className="brand serif" href="#shop"><span>M</span><b>Foundry Market</b></a><nav aria-label="Primary"><a href="#shop">Shop</a><a href="#collection">Collections</a><a href="#makers">Makers</a><a href="#journal">Journal</a></nav><div><button type="button" aria-label="Open search">⌕</button><button type="button" aria-label={'Saved items, '+saved.size}>♡ <span>{saved.size}</span></button><button type="button" aria-label="Shopping bag">Bag · 0</button></div></div></header>
    <main id="shop"><section id="collection" className="market-hero"><div><p className="eyebrow">The working room · Collection 07</p><h1>Made slowly.<br/><em>Kept for years.</em></h1><p>Independent furniture and objects chosen for material honesty, useful detail, and the pleasure of living with fewer, better things.</p><a className="button" href="#products">Explore the edit</a></div><div className="market-art" role="img" aria-label="Abstract still life of a lamp, chair and ceramic vessel"><i/><b/><span/><small>COLLECTION<br/>07 / 2026</small></div></section>
      <section id="products" className="shop"><div className="shop-title"><div><p className="label">Shop the collection</p><h2>Objects with a point of view</h2></div><label className="search"><span className="sr-only">Search products</span>⌕<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search objects"/></label></div><div className="category-row" aria-label="Product categories">{categories.map(item=><button type="button" aria-pressed={category===item} onClick={()=>setCategory(item)} key={item}>{item}</button>)}</div>
        <div className="product-grid">{visible.map((product)=>{const index=products.indexOf(product);return <article className="product" key={product[0]}><div className="product-art" style={{'--tone':product[5]}}><span>{product[4]}</span><i/><b/><button type="button" aria-pressed={saved.has(index)} aria-label={(saved.has(index)?'Remove ':'Save ')+product[0]} onClick={()=>toggle(index)}>{saved.has(index)?'♥':'♡'}</button></div><div className="product-copy"><div><h3>{product[0]}</h3><p>{product[1]} · {product[3]}</p></div><strong>{product[2]}</strong></div></article>})}</div>{!visible.length&&<p className="empty">No objects match that search. Try another category.</p>}
      </section>
      <section id="makers" className="maker-strip"><p className="label">Why Foundry</p>{[['01','Independent makers','Every purchase supports a small studio.'],['02','Material transparency','Origin and finish are documented clearly.'],['03','Delivery, handled','Insured delivery with useful updates.']].map(item=><article key={item[0]}><span>{item[0]}</span><h2>{item[1]}</h2><p>{item[2]}</p></article>)}</section>
    </main><footer><a className="brand serif" href="#shop">Foundry Market</a><p>Useful objects, independent hands.</p><nav><a href="#shop">Shipping</a><a href="#shop">Returns</a><a href="#makers">Sell with us</a></nav></footer>
  </div>
}
