import { useMemo, useState } from 'react'

const jobs=[
  ['Senior Product Designer','Northstar Health','Remote · Europe','$130–155k','Design','Full-time','2h'],['Staff Software Engineer','Common Thread','Toronto · Hybrid','$165–190k','Engineering','Full-time','5h'],['Research Lead','Public Digital Lab','London · Hybrid','£78–92k','Research','Full-time','1d'],['Founding Product Manager','Fieldnote AI','Remote · Americas','$145–175k','Product','Full-time','1d'],['Design Engineer','Ordinary Tools','Berlin · On-site','€85–105k','Engineering','Full-time','2d'],['Content Strategist','Civic Works','Remote · Global','$95–118k','Content','Contract','2d'],
]
const types=['All roles','Design','Engineering','Product','Research','Content']

export default function App(){const[query,setQuery]=useState('');const[type,setType]=useState('All roles');const[selected,setSelected]=useState(0);const[saved,setSaved]=useState(new Set([2]));const visible=useMemo(()=>jobs.filter(job=>(type==='All roles'||job[4]===type)&&[job[0],job[1],job[2]].join(' ').toLowerCase().includes(query.toLowerCase())),[query,type]);const current=visible[selected]||visible[0];const toggle=job=>setSaved(items=>{const next=new Set(items);const index=jobs.indexOf(job);next.has(index)?next.delete(index):next.add(index);return next})
  return <div className="jobs-app"><header className="jobs-head"><a className="brand" href="#jobs"><span>P</span><b>practice</b><small>Good work, clearly described.</small></a><nav aria-label="Primary"><a href="#jobs">Find work</a><a href="#companies">Companies</a><a href="#advice">Career notes</a></nav><div><a href="#employers">For employers</a><button className="button" type="button">Post a role</button></div></header>
    <main><section className="jobs-hero"><p className="eyebrow">Curated roles · Clear salary · No ghost listings</p><h1>Find work that respects<br/><em>the work.</em></h1><p>Thoughtful teams, useful products, transparent expectations. Every role is reviewed by a human and expires after 30 days.</p><form className="job-search" onSubmit={event=>event.preventDefault()}><label><span>What do you want to do?</span><input value={query} onChange={event=>{setQuery(event.target.value);setSelected(0)}} placeholder="Role, skill, or company"/></label><label><span>Where?</span><input placeholder="Remote or city"/></label><button className="button" type="submit">Search roles</button></form><div className="trust-row"><span><b>326</b> active roles</span><span><b>92%</b> show salary</span><span><b>48h</b> employer response target</span></div></section>
      <section id="jobs" className="jobs-section"><div className="job-filter"><div><p className="label">Browse roles</p><h2>{visible.length} opportunities</h2></div><div className="role-tabs" aria-label="Role type">{types.map(item=><button type="button" aria-pressed={type===item} onClick={()=>{setType(item);setSelected(0)}} key={item}>{item}</button>)}</div></div><div className="job-layout"><div className="job-list">{visible.map((job,index)=><article className={current===job?'selected':''} key={job[0]}><button className="job-open" type="button" onClick={()=>setSelected(index)}><span className="company-mark">{job[1].split(' ').map(word=>word[0]).join('').slice(0,2)}</span><span><small>{job[4]} · {job[6]}</small><h3>{job[0]}</h3><p>{job[1]}</p><i>{job[2]} · {job[3]}</i></span></button><button className="save-job" type="button" aria-pressed={saved.has(jobs.indexOf(job))} onClick={()=>toggle(job)} aria-label={(saved.has(jobs.indexOf(job))?'Unsave ':'Save ')+job[0]}>{saved.has(jobs.indexOf(job))?'♥':'♡'}</button></article>)}{!visible.length&&<p className="empty">No current roles match those filters.</p>}</div>{current&&<aside className="job-detail"><div className="detail-top"><span className="company-mark large">{current[1].split(' ').map(word=>word[0]).join('').slice(0,2)}</span><p className="label">Featured role</p><h2>{current[0]}</h2><p>{current[1]} · {current[2]}</p><strong>{current[3]}</strong></div><div className="detail-copy"><h3>The work</h3><p>Own a meaningful product area from early discovery through shipped details. You will work closely with engineering, research, and customers without a handoff-heavy process.</p><h3>What matters here</h3><ul><li>Strong judgment and clear written thinking</li><li>Comfort working directly with customers</li><li>A portfolio that explains decisions, not just outcomes</li></ul></div><a className="button wide" href="mailto:jobs@practice.example">Apply with your work →</a><small>Application reviewed by a person · Usually replies in 5 days</small></aside>}</div></section>
      <section id="employers" className="employer"><div><p className="eyebrow">Hiring with respect</p><h2>Describe the real job.<br/>Meet better candidates.</h2></div><div><p>Every listing includes salary, working location, interview steps, and an expiry date. We reject vague roles and unpaid exercises.</p><button className="button inverse" type="button">Post a role · $249</button></div></section>
    </main><footer><a className="brand" href="#jobs">practice</a><p>Good work, clearly described.</p><nav><a href="#jobs">Guidelines</a><a href="#employers">Pricing</a><a href="mailto:hello@practice.example">Contact</a></nav></footer>
  </div>
}
