import { useState } from 'react'

const starters = ['Summarize this research', 'Draft a launch brief', 'Compare the three options']
const initial = [
  { role: 'user', text: 'Turn the attached customer interviews into a launch recommendation for the analytics add-on.' },
  { role: 'assistant', text: 'The strongest launch angle is decision speed, not more reporting. Across 18 interviews, teams repeatedly described the cost of waiting for an analyst.', points: ['Position it as an answer layer over existing dashboards.', 'Lead with a 14-day decision-speed benchmark.', 'Keep the first release focused on saved questions and cited answers.'] },
]

export default function App(){
  const [messages,setMessages]=useState(initial); const [prompt,setPrompt]=useState(''); const [model,setModel]=useState('Aperture Pro'); const [sources,setSources]=useState(true)
  const send=()=>{const value=prompt.trim();if(!value)return;setMessages(items=>[...items,{role:'user',text:value},{role:'assistant',text:'I have turned that into a concise working draft. The next useful step is to validate the primary claim with the attached interview evidence.',points:['State the decision and intended reader first.','Attach one source to every external claim.','End with an owner and a review date.']}]);setPrompt('')}
  return <div className="app ai-app">
    <aside className="ai-nav"><a className="brand light" href="#chat"><span>A</span><b>aperture</b></a><button className="new-chat" type="button">＋ New thread</button><nav aria-label="Conversation history"><p>Today</p>{['Analytics launch brief','Interview synthesis','Board memo outline'].map((item,index)=><a className={index===0?'active':''} href="#chat" key={item}>◇ {item}</a>)}<p>Previous</p>{['Pricing objections','Q3 planning notes'].map(item=><a href="#chat" key={item}>◇ {item}</a>)}</nav><div className="usage"><span><b>72%</b> monthly usage</span><i><b /></i><a href="#settings">Manage plan</a></div></aside>
    <main id="chat" className="chat"><header className="chat-head"><div><p className="eyebrow">Shared with Product</p><h1>Analytics launch brief</h1></div><div><button className="ghost dark" type="button">Share</button><button className="ghost dark" type="button" aria-label="More conversation actions">•••</button></div></header>
      <div className="chat-body"><section className="thread" aria-label="AI conversation">{messages.map((message,index)=><article className={'message '+message.role} key={index}><span className="avatar">{message.role==='user'?'KM':'A'}</span><div><p className="message-label">{message.role==='user'?'You':model}</p><p>{message.text}</p>{message.points&&<ul>{message.points.map(point=><li key={point}>{point}</li>)}</ul>}{message.role==='assistant'&&sources&&<div className="citations"><a href="#source-1">1 · Interview synthesis</a><a href="#source-2">2 · Usage analysis</a></div>}</div></article>)}</section>
        <div className="suggestions">{starters.map(item=><button type="button" onClick={()=>setPrompt(item)} key={item}>{item} ↗</button>)}</div>
        <form className="composer" onSubmit={event=>{event.preventDefault();send()}}><label className="sr-only" htmlFor="prompt">Message Aperture</label><textarea id="prompt" value={prompt} onChange={event=>setPrompt(event.target.value)} placeholder="Ask, draft, compare, or analyze…" rows="3"/><div><button className="attach" type="button" aria-label="Attach a file">＋</button><span>4 sources available</span><button className="send" type="submit">Send ↑</button></div></form><p className="disclaimer">Aperture can make mistakes. Verify decisions and cited evidence.</p>
      </div>
    </main>
    <aside id="settings" className="context"><div className="context-head"><p className="label">Run settings</p><h2>Context</h2></div><label>Model<select value={model} onChange={event=>setModel(event.target.value)}><option>Aperture Pro</option><option>Aperture Fast</option><option>Aperture Reason</option></select></label><label className="switch"><span><b>Use citations</b><small>Link claims to workspace files</small></span><input type="checkbox" checked={sources} onChange={event=>setSources(event.target.checked)}/></label><div className="source-list"><p className="label">Included sources</p>{[['PDF','Interview synthesis.pdf','2.8 MB'],['CSV','Usage cohorts.csv','840 KB'],['DOC','Launch strategy.docx','1.2 MB'],['URL','Competitor notes','Saved page']].map(([type,name,size])=><article key={name}><span>{type}</span><p><b>{name}</b><small>{size}</small></p><button type="button" aria-label={'Remove '+name}>×</button></article>)}</div></aside>
  </div>
}
