import ClayProgress from'./ClayProgress.jsx'
const habits=[['Morning water','drop',true],['Read ten pages','book',true],['Evening walk','walk',false]]
const icons={drop:<path d="M12 2S6 9 6 14a6 6 0 0 0 12 0c0-5-6-12-6-12Z"/>,book:<><path d="M4 5h6a3 3 0 0 1 3 3v12H7a3 3 0 0 0-3 1Z"/><path d="M20 5h-6a3 3 0 0 0-3 3v12h6a3 3 0 0 1 3 1Z"/></>,walk:<><circle cx="13" cy="5" r="2"/><path d="m10 22 2-7-3-3 2-4 4 3 4 1M12 15l5 7"/></>}
function Icon({name}){return <svg viewBox="0 0 24 24" aria-hidden="true">{icons[name]}</svg>}
function Status(){return <div className="phone-top"><span>9:41</span><span className="status-icons"><i/><i/><b/></span></div>}
function BottomNav({active='today'}){return <div className="bottom-nav"><span className={active==='today'?'active':''}><b>⌂</b>Today</span><span className={active==='garden'?'active':''}><b>✿</b>Garden</span><span className={active==='reflect'?'active':''}><b>◌</b>Reflect</span></div>}
function GardenScene(){return <svg className="garden-scene" viewBox="0 0 320 210" role="img" aria-label="A small garden growing across the month"><defs><linearGradient id="garden-sky" x2="0" y2="1"><stop stopColor="#ddecf5"/><stop offset="1" stopColor="#f9e6c5"/></linearGradient></defs><rect width="320" height="210" rx="25" fill="url(#garden-sky)"/><circle cx="258" cy="48" r="25" fill="#ffd28c"/><path d="M0 145Q55 110 112 145T223 141T320 128V210H0Z" fill="#a9d2ad"/><path d="M0 172Q76 136 153 174T320 158V210H0Z" fill="#82b58f"/>{[[44,155,'#ff9a86'],[92,139,'#fff3a1'],[146,169,'#c29bdd'],[205,143,'#ff9a86'],[269,154,'#fff3a1']].map(([x,y,c],i)=><g key={x}><path d={`M${x} ${y+31}V${y}`} stroke="#4d8660" strokeWidth="5"/><circle cx={x} cy={y} r={10+i%2*4} fill={c}/><circle cx={x} cy={y} r="4" fill="#fff7d2"/></g>)}<path d="M12 192Q80 168 142 192T302 184" fill="none" stroke="#547c5c" strokeOpacity=".35" strokeWidth="3"/></svg>}
function WeekChart(){return <div className="week-chart"><div className="week-labels"><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span><span>S</span></div><div className="week-dots">{[1,1,1,1,0,1,1].map((v,i)=><i className={v?'filled':''} key={i}>{v?'✓':''}</i>)}</div></div>}
export default function Phone({screen='today',className=''}){return <div className={`phone ${className}`}><div className="phone-shell"><div className="phone-notch"/><div className={`phone-screen screen-${screen}`}><Status/>
{screen==='today'&&<><div className="screen-heading"><div><p className="tiny-kicker">TUESDAY, MAY 12</p><h3>Good morning,<br/>Mia <span>🌤️</span></h3></div><button aria-label="Open profile">M</button></div><div className="streak"><span>7</span><p><b>day rhythm</b><small>You’re growing steadily.</small></p><em>↗</em></div><WeekChart/><div className="habit-head"><span>TODAY’S MOMENTS</span><b>2 / 3</b></div><div className="habit-list">{habits.map(([n,e,done])=><div key={n} className={done?'done':''}><i><Icon name={e}/></i><span>{n}<small>{done?'Beautifully done':'Ready when you are'}</small></span><b>{done?'✓':'+'}</b></div>)}</div><BottomNav/></>}
{screen==='garden'&&<><div className="screen-heading"><div><p className="tiny-kicker">YOUR GARDEN</p><h3>Small steps<br/>in bloom.</h3></div><button aria-label="May calendar">MAY</button></div><GardenScene/><ClayProgress value={78} label="May’s rhythm"/><div className="garden-stats"><span><b>22</b>gentle days</span><span><b>64</b>moments kept</span></div><p className="screen-note">No perfect streak required. Your garden remembers the return.</p><BottomNav active="garden"/></>}
{screen==='reflect'&&<><div className="screen-heading"><div><p className="tiny-kicker">EVENING NOTE</p><h3>How did today<br/>feel?</h3></div><button aria-label="Close reflection">×</button></div><p className="mood-prompt">Choose the weather that fits.</p><div className="moods"><button aria-label="A difficult day">☁️</button><button aria-label="An okay day">🌤️</button><button className="selected" aria-label="A good day">☀️</button></div><label className="note-label">ONE THING TO REMEMBER</label><div className="note-card">I had more energy after my walk. Keep lunch simple tomorrow.<span>74 / 180</span></div><div className="reflection-tags"><button>Calm</button><button className="active">Energized</button><button>Connected</button></div><button className="save-note">Save today <span>→</span></button><BottomNav active="reflect"/></>}
<div className="phone-home"/></div></div></div>}
